server:
  port: ${PORT:12010}

spring:
  application:
    name: tsuu-edge
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      httpclient:
        connect-timeout: 45000
        response-timeout: 45s
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    net.sandrohc.tsuu: INFO